# 위 사진 노란색 박스 action name이 될 것임.
name: my-front

# 메인브랜치로 푸시
on:
  push:
    branches:
      - main



jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AKIATWM5VVS3TOIFUSYP }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.IjqU2DRaXvAUUreeClc5pk7G4ocPE5PVabpie197 }}
      AWS_REGION: 'ap-northeast-2'

    steps:
      - name: Checkout source code.
        uses: actions/checkout@master

      - name: Upload binary to S3 bucket
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --exclude '*' --include 'index.html'
        env:
          AWS_S3_BUCKET: ${{ secrets.spartagora }}

      - name: Invalidate cache CloudFront
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{ secrets.E257HZK2PLT4UM }}
          PATHS: '/index.html'
        continue-on-error: true